---
Name: 'nswdpc-asset-scan-handling'
---
NSWDPC\AssetScan\Backend:
  max_chunk_size: 1048576
SilverStripe\Core\Injector\Injector:
  NSWDPC\AssetScan\Backend:
    # set default backend
    class: 'NSWDPC\AssetScan\ClamAVBackend'
